# SPDX-License-Identifier: Apache-2.0
version: "3"

volumes:
  pgdata:
  walletstore:

networks:
  test:
    external:
      name: test

services:
  explorerdbmynetworkcom:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.amandigital.net
    hostname: explorerdb.amandigital.net
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      test:
        aliases:
          - explorerdb.amandigital.net

  explorermynetworkcom:
    deploy:
      placement:
       constraints:
         - node.labels.name == manager
    image: hyperledger/explorer:latest
    container_name: explorer.amandigital.net
    hostname: explorer.amandigital.net
    environment:
      - DATABASE_HOST=explorerdb.amandigital.net
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./first-network.json:/opt/explorer/app/platform/fabric/first-network.json
      - ../test-network/organizations:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - 8080:8080
    depends_on:
      - explorerdbmynetworkcom
    networks:
      test:
        aliases:
          - explorer.amandigital.net
