- name: Run CouchDB container
  hosts: peer_servers
  become: yes
  tasks:
    - name: Run CouchDB Docker container
      community.docker.docker_container:
        name: couchdb
        image: couchdb:3.1.1
        state: started
        restart_policy: always
        published_ports:
          - "{{ couchdb_port }}:5984"
        env:
          COUCHDB_USER: admin
          COUCHDB_PASSWORD: adminpw
