---
- name: Ensure environment variables are set in .profile
  hosts: orderer_servers
  tasks:
    - name: Create systemd service file for Fabric CA Server
      become: yes
      template:
        src: templates/fabric-ca-server.service.j2
        dest: /etc/systemd/system/fabric-ca-server.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd daemon
      become: yes
      command: systemctl daemon-reload

    - name: Enable and start Fabric CA Server service
      become: yes
      systemd:
        name: fabric-ca-server
        enabled: yes
        state: started

