---
- name: Ensure environment variables are set in .profile
  hosts: peer_servers
  tasks:


    - name: Run registerEnroll.sh and createOrderer
      shell: |
        . ./organizations/fabric-ca/registerEnroll.sh
        create{{ inventory_hostname[0] | upper }}{{ inventory_hostname[1:] }}
      args:
        executable: /bin/bash
        chdir: /home/ubuntu/hlf-docker-swarm/test-network
      when: not orderer_ca_cert.stat.exists

    - name: Fetch files from remote to local
      fetch:
        src: "/home/ubuntu/hlf-docker-swarm/test-network/organizations/peerOrganizations/{{ inventory_hostname }}.amandigital.net"
        dest: "../test-network/organizations/peerOrganizations/{{ inventory_hostname }}"
        flat: yes